apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: python-app-svc
  selector:
    app: python-app
