apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-apps
data:
  python_app_RABBITMQ_HOSTNAME: "192.168.105.1" #Rabbitmq-nodeport.default
  python_app_RABBITMQ_PORT: "5672"
  python_app_RABBITMQ_PROTOCOL: "amqp://"
